### ISSUE TITLE
Application run failed

### ISSUE THREAD

**Issue by nimitsolanki** [aakashsankritya/Doctors-Appointment-Booking-App-backend#2]
![Screenshot 2021-03-08 at 3 53 50 PM](https://user-images.githubusercontent.com/12393290/110291206-9ca36a80-8026-11eb-80ae-fc0485772cea.png)

**Comment by aakashsankritya** [comment]
Yes, this was supposed to happen. 

Actually, for security reason I have removed the database configuration from `src/main/resources/application.properties`

- Please check your `application.properties` file. 
- There you need to declare your database configurations and since the backend is using MongoDB as its database. 
- Try to use mongo's configuration (either local or MongoDB Atlas).
- **Also update this property in same file `file.upload-dir` pointing to some local directory, it should not be null.**

Revert me back if the problem persists.

**Comment by nimitsolanki** [comment]
Thanks, it's resolved. Now stuck at <=========----> 75% EXECUTING
It will be great if you can post the "Steps to Run" in the readme section.

**Comment by aakashsankritya** [comment]
- Check http://localhost:8081/ the server would be up now.
- Sure, I will update the steps in the readme section.
